import {config} from 'dotenv';

config({ path: `.env.${process.env.NODE_ENV || "development"}.local` });

export const { 
    SYSTEM_NAME,
      PORT,
  SERVER_URL,
  NODE_ENV,
  MONGO_URI,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN,
  STUDENT_JWT_SECRET,
  STUDENT_JWT_REFRESH_SECRET,
  ARCJET_KEY,
  ARCJET_ENV,
  QSTASH_URL,
  QSTASH_TOKEN,
  QSTASH_CURRENT_SIGNING_KEY,
  QSTASH_NEXT_SIGNING_KEY,
  EMAIL_PASSWORD,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  MAX_LOGIN_ATTEMPTS,
  PRODUCTION_URL,
  EMAIL_HOST
 } = process.env;